### ISSUE TITLE
Product not available on Chrome store anymore

### ISSUE THREAD

**Issue by forsanger** [yurist38/linkedin-video-downloader#30]
### Expected outcome
Hoping for another way of using the plugin, without the vetting of Google Chrome Web Store

**Comment by yurist38** [comment]
Unfortunately, Google Web Store blocked this extension recently due to a complaint from LinkedIn. That's very sad but I will add here the built extension file that you can download and use directly. Will update you on this shortly.

**Comment by yurist38** [comment]
Just updated this repo with the CRX file, please check the updated README for more context. I think we can close this issue now. Thanks!

**Comment by forsanger** [comment]
Thank you will try it :-)
